#!/bin/bash

SHELL_DIR=${0}
MYNAME=${0##*/}

readonly SHORT_OPT="hn:o"
readonly LONG_OPT="help,name:,overwrite"

_help() {
    cat <<EOF
Usage: valve `basename $0` {Params...}

Params:
    h, help                 현재 화면을 보여줍니다.

    n, name                 Not yet
    o, overwrite            Not yet

================================================================================
EOF
}

_run() {

    OPTIONS=$(getopt -l "${LONG_OPT}" -o "${SHORT_OPT}" -a -- "$@")
    eval set -- "${OPTIONS}"

    while [ $# -gt 0 ]; do
        case "$1" in
            -n|--name)
                echo "n name option"
                ;;
            -o|--overwrite)
                echo "o overwrite option"
                ;;
            -h|--help)
                _help
                exit 0
                ;;
            --)
                # No more options left.
                _help
                shift
                break
               ;;
        esac
        shift
    done

}

_run $@

