#!/bin/bash

CUR_DIR=${0%/*}
CUR_NAME=${0##*/}

readonly PLUGINS_DIR=${CUR_DIR}/${CUR_NAME}-cmds

####### common functions
source ${ROOT_PLUGINS_DIR}/common.sh

##### 새 기능의 모체 추가할때
# 1. help message 추가
# 2. _set_cmd function 내 case 추가
# 3. 현재 스크립트의 위치에 ${현재스크립트이름}-cmds directory 가 존재해야 하며 
#   directory 내에는 정의한 command (long) 와 일치하는 스크립트(chmod +x)가 존재해야 함.

# 1 point. help message 추가
_help() {
    cat <<EOF
================================================================================
Usage: valve ${CUR_NAME} {Params}

Params:
    h, help                 현재 화면을 보여줍니다.

    i, install              Not yet (TODO 도구들을 설치합니다.)

================================================================================
EOF
}

# Define short command
_set_cmd() {
    case $CMD in
# 2 point. _set_cmd function 내 case 추가
        h)
            CMD=help
            ;;
        i)
            CMD=install
            ;;
    esac
}

_run() {
    # check first param
    if [ ! -z $1 ]; then
        CMD=$1
    else
        _help
        _success
    fi

    # replace short cmd to long cmd
    _set_cmd

    ### Use another script, if exist ###
    # check if exist plugin
    if [ ! -f $PLUGINS_DIR/$CMD ]; then
        _help
        _error "No params: $1, $CMD"
    fi

    # RUN plugin command
    shift
    $PLUGINS_DIR/${CMD} $*

}


_run $@

