FROM docker-registry-devops.coruscant.opsnow.com/rbatch-base:v0.0.1-20191023-0854

ADD sources/Batchcode.R /usr/local/src/sources/Batchcode.R
ADD sources/Functions.R /usr/local/src/sources/Functions.R
WORKDIR /usr/local/src/sources