#!/bin/bash

CUR_DIR=${0%/*}
CUR_OBJECT=`echo $CUR_DIR | cut -d "/" -f6`
CUR_NAME=${0##*/}

####### common functions
source ${ROOT_SHELL_DIR}/common.sh

readonly SHORT_OPT="hvn:u:"
readonly LONG_OPT="help,verbose,name:,url:"

_help() {
    cat <<EOF
================================================================================
Usage: valve ${CUR_OBJECT} ${CUR_NAME}

Params:
    -h, --help                                          현재 화면을 보여줍니다.

    -n, --name                      (requirement)       템플릿의 이름을 추가합니다.
    -u, --url                       (requirement)       템플릿의 주소를 추가합니다.

Examples:
    [Mandatory]
    $ cd {PROJECT}
    $ valve repo add --name example --url git@github.com:example/examgle.git
================================================================================
EOF
}

_run() {
    OPTIONS=$(getopt -l "${LONG_OPT}" -o "${SHORT_OPT}" -a -- "$@"  2>${CUR_DIR}/.tmp)
    if  [ $? -eq 1 ]; then
        _help
        _error "Error params: `cat ${CUR_DIR}/.tmp && rm -f ${CUR_DIR}/.tmp `"
    elif ! [[ $@ =~ '-' ]]; then
        _help
        _error "Error params: $@"
    fi
    eval set -- "${OPTIONS}"

    while [ $# -gt 0 ]; do
        case "$1" in
            -n|--name)
                shift
                PARAMS_NAME=$1
                ;;
            -u|--url)
                shift
                PARAMS_URL=$1
                ;;
            -h|--help)
                _help
                exit 0
                ;;
            -v|--verbose)
                DEBUG_MODE=true
                VERBOSE=$(($VERBOSE + 1))
                ;;
            --)
                shift
                break
               ;;
        esac
        shift
    done

    if [ ! -z ${PARAMS_NAME} ] && [ ! -z ${PARAMS_URL} ]; then
        _add
    else
        _help
        _error "Use valve repo add -h or valve repo add --help"
    fi
}

##################################################################################
_add() {
    _debug_mode
    WARNING=0
    #_command "cat ${CONFIG} | grep ${PARAMS_NAME} | grep ${PARAMS_URL} | wc -l | xargs"
    CNT=$(cat ${CONFIG} | grep "${PARAMS_NAME}" | wc -l | xargs)
    CNT_TITLE=$(cat ${CONFIG} | grep "REPO LIST" | wc -l | xargs)

    # Count Repository
    if [ -d ${CONFIG_DIR}/repo/${PARAMS_NAME} ]; then
        pushd ${CONFIG_DIR}/repo/${PARAMS_NAME} > /dev/null
        git config --get remote.origin.url | head -1
        CNT_REPO=$(git config --get remote.origin.url | head -1 | wc -l)
        CHECK_URL=$(git config --get remote.origin.url | head -1)
        popd > /dev/null
        if [ ${CHECK_URL} == ${PARAMS_URL} ]; then
            CNT_REPO=1
        else
            CNT_REPO=2
        fi
    else
        CNT_REPO=0
    fi

    if [ ${CNT} -eq 1 -a ${CNT_REPO} -eq 0 ]; then
        _warning "There is a config...  but no repository. Register repository automated..!"
        __register_repo
        _success "Register repository success"
    elif [ ${CNT} -eq 0 -a ${CNT_REPO} -eq 2 ]; then
        _error "Check this URL = "${CHECK_URL}
    elif [ ${CNT} -eq 0 -a ${CNT_REPO} -eq 1 ]; then
        _warning "There is a repo.. but not in config file. Register config automated..!"
        __apply_url
        __register_config
        _success "Register config success"
    elif [ ${CNT} -eq 1 -a ${CNT_REPO} -eq 1 ]; then
        _error "There is a same repo in config file. Register another name & url"
    else
        __register_repo
        __register_config
        _success "Register repository success"
    fi
}

__register_config() {
    # Check Title & marking in config
    if [ ! ${WARNING} -eq 1 ]; then
        if [ ${CNT_TITLE} -eq 1 ]; then
cat <<EOF >> ${CONFIG}
# ${PARAMS_NAME} ${PARAMS_URL}
EOF
        cat ${CONFIG}
        else
cat <<EOF >> ${CONFIG}
### REPO LIST ###
# ${PARAMS_NAME} ${PARAMS_URL}
EOF
        cat ${CONFIG}
        fi
    fi
}

__apply_url() {
    PARAMS_URL=${CHECK_URL}
}

__register_repo() {
    # Install Custom templates
    if [ -d ${CONFIG_DIR}/repo ]; then
        pushd ${CONFIG_DIR}/repo > /dev/null
        GIT_RES=$(git clone ${PARAMS_URL} ${PARAMS_NAME} 2>&1)
        
        if [ $? -eq 128 ]; then             ## git error
            if [[ ${GIT_RES} =~ "destination" ]]; then
                WARNING=1
                _error "Same Repository here"
            elif [[ ${GIT_RES} =~ "repository" ]]; then
                WARNING=1
                _error "Repository not found"
            elif [[ ${GIT_RES} =~ "Warning" ]]; then
                WARNING=1
                _error "SSH key should register your git repository."
            elif [[ ${GIT_RES} =~ "Authentication" ]]; then
                WARNING=1
                _error "Invalid username or password"
            fi
        else
            WARNING=0
        fi
        popd > /dev/null
    else
        _error "Install first..!"
    fi
}
##################################################################################

_run $@