#!/bin/bash

CUR_DIR=${0%/*}
CUR_OBJECT=`echo $CUR_DIR | cut -d "/" -f6`
CUR_NAME=${0##*/}

####### common functions
source ${ROOT_SHELL_DIR}/common.sh

_help() {
    cat <<EOF
================================================================================
Usage: valve ${CUR_OBJECT} ${CUR_NAME}                  템플릿이 존재하는 레파지토리를 보여줍니다.

Examples:
    [Mandatory]
    $ cd {PROJECT}
    $ valve repo list
================================================================================
EOF
}

_run() {
    _list
}

##################################################################################
_list() {
    # _protocol="$(echo ${_u} | grep :// | sed -e's,^\(.*://\).*,\1,g')"
    # _url=$(echo ${_u} | sed -e s,$_protocol,,g)
    # _path=$(echo ${_url} | awk -F'.' '{print $(NF-1)}' | awk -F'/' '{print $NF}')
    echo -e "[Repository Name]\011[Url]"
    sed '1,/REPO/d' ${CONFIG} | awk -v OFS='\011\011\011' '{print $2,$3}'
}
##################################################################################

_run $@