#!/bin/bash

CUR_DIR=${0%/*}
CUR_OBJECT=`echo $CUR_DIR | cut -d "/" -f6`
CUR_NAME=${0##*/}

####### common functions
source ${ROOT_SHELL_DIR}/common.sh

_help() {
    cat <<EOF
================================================================================
Usage: valve ${CUR_OBJECT} ${CUR_NAME} 

Examples:
    [Mandatory]
    $ cd {PROJECT}
    $ valve repo list
================================================================================
EOF
}

_run() {
    _list
}

##################################################################################
_list() {
    # _protocol="$(echo ${_u} | grep :// | sed -e's,^\(.*://\).*,\1,g')"
    # _url=$(echo ${_u} | sed -e s,$_protocol,,g)
    # _path=$(echo ${_url} | awk -F'.' '{print $(NF-1)}' | awk -F'/' '{print $NF}')
    echo -e "[Template]\t\t[Name]\t\t[Custom Template Url]"
    sed '1,/REPO/d' ${CONFIG} | awk -F' ' '{print $4,"\t",$2,"\t",$3}'
}
##################################################################################

_run $@