#!/bin/bash

CUR_DIR=${0%/*}
CUR_OBJECT=`echo $CUR_DIR | cut -d "/" -f6`
CUR_NAME=${0##*/}

####### common functions
source ${ROOT_SHELL_DIR}/common.sh

readonly SHORT_OPT="hvn:u:"
readonly LONG_OPT="help,verbose,name:,url:"

_help() {
    cat <<EOF
================================================================================
Usage: valve ${CUR_OBJECT} ${CUR_NAME}
Params:
    -h, --help                                          현재 화면을 보여줍니다.
    -n, --name                      (requirement)       레파지토리를 최신화 합니다.
Examples:
    [Mandatory]
    $ cd {PROJECT}
    $ valve repo update --name example
================================================================================
EOF
}

_run() {
    OPTIONS=$(getopt -l "${LONG_OPT}" -o "${SHORT_OPT}" -a -- "$@"  2>${CUR_DIR}/.tmp)
    if  [ $? -eq 1 ]; then
        _help
        _error_noreport "Error params: `cat ${CUR_DIR}/.tmp && rm -f ${CUR_DIR}/.tmp `"
    elif ! [[ $@ =~ '-' ]]; then
        _help
        _error_noreport "Error params: $@"
    fi
    eval set -- "${OPTIONS}"

    while [ $# -gt 0 ]; do
        case "$1" in
            -n|--name)
                shift
                PARAMS_NAME=$1
                ;;
            -h|--help)
                _help
                exit 0
                ;;
            -v|--verbose)
                DEBUG_MODE=true
                VERBOSE=$(($VERBOSE + 1))
                ;;
            --)
                shift
                break
               ;;
        esac
        shift
    done

    if [ ! -z ${PARAMS_NAME} ]; then
        _update
    else
        _help
        _error_noreport "Use valve repo add -h or valve repo add --help"
    fi
}

##################################################################################
_update() {
    _debug_mode

    if [ -d "${CONFIG_DIR}/repo/${PARAMS_NAME}" ]; then
        command_chk_exitcode "pushd ${CONFIG_DIR}/repo/${PARAMS_NAME} > /dev/null"
        command_chk_exitcode "git pull > /dev/null 2>&1"
        command_chk_exitcode "popd > /dev/null"
        _result "${PARAMS_NAME} Repo Update!"
    else
        _error "There is no update repository. Check command 'valve repo list'."
    fi

}
##################################################################################

_run $@
