#!/bin/bash

CUR_DIR=${0%/*}
CUR_OBJECT=`echo $CUR_DIR | cut -d "/" -f6`
CUR_NAME=${0##*/}

####### common functions
source ${ROOT_SHELL_DIR}/common.sh


readonly SHORT_OPT="v,e"
readonly LONG_OPT="verbose,edit"

_help() {
    cat <<EOF
================================================================================
Usage: valve ${CUR_NAME} {Params}                       valve-ctl의 config를 확인합니다.

Examples:
    [Mandatory]
    $ valve config
================================================================================
EOF
}

_run() {

    OPTIONS=$(getopt -l "${LONG_OPT}" -o "${SHORT_OPT}" -a -- "$@"  2>${CUR_DIR}/.tmp)
    if  [ $? -eq 1 ]; then
        _help
        _error "Error params: `cat ${CUR_DIR}/.tmp && rm -f ${CUR_DIR}/.tmp `"
    # elif ! [[ $@ =~ '-' ]]; then
    #     _help
    #     _error "Error params: $@"
    fi
    eval set -- "${OPTIONS}"

    while [ $# -gt 0 ]; do
        case "$1" in
            -v|--verbose)
                DEBUG_MODE=true
                VERBOSE=$(($VERBOSE + 1))
                ;;
            -e|--edit)
                EDIT_MODE=true
                ;;
            --)
                shift
                break
                ;;
        esac
        shift
    done

    if [ -z ${EDIT_MODE} ]; then
        _config
    else
        _config_edit
    fi
}

##################################################################################

_config() {
    _debug_mode
    
    echo -e
    cat ${CONFIG}

    _success
}

_config_edit() {
    _debug_mode

    _result "Edit mode entering..."
    sleep 2
    m1=$(md5sum "${CONFIG}")
    vi ${CONFIG}
    echo -e
    m2=$(md5sum "${CONFIG}")
    cat ${CONFIG}
    if [ "$m1" != "$m2" ]; then
        _success "File has changed!! Check this config"
    else
        _success "File has not changed!"
    fi
}
##################################################################################

_run $@