#!/bin/bash

CUR_DIR=${0%/*}
CUR_OBJECT=`echo $CUR_DIR | cut -d "/" -f6`
CUR_NAME=${0##*/}

####### common functions
source ${ROOT_SHELL_DIR}/common.sh


readonly SHORT_OPT="v"
readonly LONG_OPT="verbose"

_help() {
    cat <<EOF
================================================================================
Usage: valve ${CUR_NAME} {Params}                       valve-ctl 및 설치된 툴의 version을 확인합니다.

Examples:
    [Mandatory]
    $ valve version
================================================================================
EOF
}

_run() {

    OPTIONS=$(getopt -l "${LONG_OPT}" -o "${SHORT_OPT}" -a -- "$@"  2>${CUR_DIR}/.tmp)
    if  [ $? -eq 1 ]; then
        _help
        _error "Error params: `cat ${CUR_DIR}/.tmp && rm -f ${CUR_DIR}/.tmp `"
    # elif ! [[ $@ =~ '-' ]]; then
    #     _help
    #     _error "Error params: $@"
    fi
    eval set -- "${OPTIONS}"

    while [ $# -gt 0 ]; do
        case "$1" in
            -v|--verbose)
                DEBUG_MODE=true
                VERBOSE=$(($VERBOSE + 1))
                ;;
            --)
                shift
                break
                ;;
        esac
        shift
    done

    _version
}

##################################################################################

_version() {
    _debug_mode

    _command "kubectl version"
    kubectl version

    _command "helm version"
    helm version

    _command "valve version"
    _echo "${THIS_VERSION}"

    _success
}
##################################################################################

_run $@