replicaCount: 1
image:
  repository: acme
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 1000m
    memory: 2048Mi
readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 6
livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 6
ingress:
  enabled: true
  basedomain: 127.0.0.1.nip.io
  hosts:
    - acme.opsnow.com
hpa:
  enabled: true
  min: 1
  max: 5
  cpu: 80
  mem: 80
profile: default
