#!/bin/bash

CUR_DIR=${0%/*}
CUR_OBJECT=`echo $CUR_DIR | cut -d "/" -f6`
CUR_NAME=${0##*/}

####### common functions
source ${ROOT_SHELL_DIR}/common.sh

##### 새 기능을 추가할때
# 1. OPT 추가
# 2. help message 추가
# 3. run function 내 case 추가
# 4. public function (api) 은 _ 로 시작, private function 은 __ 로 시작


# 1 point. OPT 추가
readonly SHORT_OPT="habc:"
readonly LONG_OPT="help,along,blong,clong:"

# 2 point. help message 추가
_help() {
    cat <<EOF
================================================================================
Usage: valve ${CUR_OBJECT} ${CUR_NAME} {Params}

Params:
    -h, --help                  현재 화면을 보여줍니다.

    -a, --along                 a option
    -b, --blong                 b option
    -c, --clong                 c option
        cparam                      c parameter

================================================================================
EOF
}

_run() {

    OPTIONS=$(getopt -q -l "${LONG_OPT}" -o "${SHORT_OPT}" -a -- "$@" 2>${CUR_DIR}/.tmp)
    if  [ $? -eq 1 ]; then
        _help
        _error "Error params: `cat ${CUR_DIR}/.tmp && rm -f ${CUR_DIR}/.tmp `"
    elif ! [[ $@ =~ '-' ]]; then
        _help
        _error "Error params: $@"
    fi
    eval set -- "${OPTIONS}"
    
    while [ $# -gt 0 ]; do
# 3 point. case 추가
        case "$1" in
            -a|--along)
                _aoption
                ;;
            -b|--blong)
                _boption
                ;;
            -c|--clong)
                shift;
                PARAM=$1
                echo "c opt param : $PARAM"
                ;;
            -h|--help)
                _help
                exit 0
                ;;
            --)
                # No more options left.
                shift
                break
               ;;
        esac
        shift
    done

}

##################################################################################
# 4 point. function 추가
_aoption() {
    _result "CUR_DIR : ${CUR_DIR}"
    _result "CUR_NAME : ${CUR_NAME}"
    
    _command "a option"
}

_boption() {
    _result "public b func"
    __private_bopt
}

__private_bopt() {
    _result "private b func"
}

##################################################################################

_run $@

