{{ if .Values.ingress.enabled }}
{{- $fullName := include "fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
{{ if not (empty .Values.ingress.basedomain) }}
  - host: {{ .Release.Name }}.{{ .Values.ingress.basedomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{ end }}
{{ range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $servicePort }}
{{ end }}
{{ if (not (empty .Values.ingress.tls)) }}
  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.ingress.basedomain }}
    secretName: {{ template "fullname" . }}-tls
{{ end }}
{{ end }}
