# ------------------- Deployment ------------------- #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node
  namespace: default
  labels:
    app: sample-node
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
  selector:
    matchLabels:
      k8s-app: sample-node
  template:
    metadata:
      labels:
        k8s-app: sample-node
    spec:
      containers:
      - name: sample-node
        image: quay.io/nalbam/sample-node
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 15
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        # envFrom:
        # - configMapRef:
        #     name: configmap

---
# ------------------- Service ------------------- #

apiVersion: v1
kind: Service
metadata:
  name: sample-node
  namespace: default
  labels:
    app: sample-node
spec:
  # type: SERVICE_TYPE
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    k8s-app: sample-node

---
# ------------------- Ingress ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sample-node
  namespace: default
  labels:
    app: sample-node
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: INGRESS_DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: sample-node
          servicePort: 80

---
# ------------------- HorizontalPodAutoscaler ------------------- #

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-node
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-node
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 66
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 66
