apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        app: {{ template "fullname" . }}
        version: master
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        resources:
{{ toYaml .Values.resources | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        env:
          - name: PROFILE
            value: {{ .Values.profile }}
{{ if or .Values.configmap.enabled .Values.secret.enabled }}
        envFrom:
{{ end }}
{{ if .Values.configmap.enabled }}
          - configMapRef:
              name: {{ template "fullname" . }}
{{ end }}
{{ if .Values.secret.enabled }}
          - secretRef:
              name: {{ template "fullname" . }}
{{ end }}
